version: '3.8'

services:
  jupyter-pyspark:
    build: .
    container_name: jupyter_spark_mef_dl
    ports:
      - "8101:8888"   # Jupyter Lab (8101 para evitar conflictos con el lab6)
      - "4051:4040"   # Spark UI
    volumes:
      - .:/workspace
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - GRANT_SUDO=yes
      - SPARK_DRIVER_MEMORY=6g
      - SPARK_EXECUTOR_MEMORY=6g
      - JUPYTER_TOKEN=desarrollo
      - CHOWN_HOME=yes
      - CHOWN_HOME_OPTS=-R
    restart: always
    networks:
      - spark-network
    deploy:
      resources:
        limits:
          cpus: '6'
          memory: 16G
        reservations:
          cpus: '2'
          memory: 4G

networks:
  spark-network:
    driver: bridge
